name: CD Pipeline

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Commitlint step to validate commit messages
      - name: Lint Commit Messages
        run: npx commitlint --from=origin/main --to=HEAD

      - name: Build project
        run: npm run build